version: '3'
services:
  dcos-ui:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - .:/src
      - ./testdata/docroot:/opt/mesosphere/active
    command: ["rerun", "-v", "--config=rerun.json"]
  cosmos:
    build:
      context: ./testdata/localCosmos
      dockerfile: Dockerfile
    ports:
      - 7070:7070
    volumes:
      - ./testdata/localCosmos:/opt/app
      - /opt/app/node_modules
    environment:
      - CLUSTER_URL
      - AUTH_TOKEN
    command: ["npm", "start"]    
  zookeeper:
    image: jplock/zookeeper:3.4.13
    ports:
      - "2181:2181"
    logging:
      driver: none
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./testdata/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./testdata/docroot:/opt/mesosphere/active