FROM golang:1.11
WORKDIR /src

RUN apt-get update && apt-get install -y vim python-pip groff && \
    pip install --upgrade awscli

RUN go get -u github.com/alecthomas/gometalinter github.com/t-yuki/gocover-cobertura github.com/ivpusic/rerun && \
    gometalinter --install

CMD /src/main