FROM golang:1.11.3

RUN apt-get update && apt-get install -y curl vim python-pip groff && \
    pip install --upgrade awscli

RUN go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

RUN mkdir -p /run/dcos

ADD . /src
WORKDIR /src
EXPOSE 5000